apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
spec:
  ports:
  - name: dashboard
    port: 7000
    protocol: TCP
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ceph
  namespace: rook-ceph
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: ceph.here
    http:
      paths:
        - backend:
            serviceName: rook-ceph-mgr-dashboard
            servicePort: 7000
