apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ssd
provisioner: ceph.rook.io/block
parameters:
  blockPool: ssd
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: rook-ceph
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: Retain
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ssd
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 2
  deviceClass: ssd
