# This is just for hosting touhou lossless music collection because it slows deluge down to a crawl.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deluge-tlmc
  labels:
    app: deluge-tlmc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge-tlmc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge-tlmc
    spec:

      hostNetwork: true
      containers:
      - name: deluge
        image: linuxserver/deluge
        ports:
        - containerPort: 8112
          name: webold
        - containerPort: 58846
          name: client
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: "America/Toronto"
        volumeMounts:
        - mountPath: /mnt
          name: mnt
        - mountPath: /config
          name: config
      volumes:
      - name: mnt
        persistentVolumeClaim:
          claimName: cephfs-pvc
      - name: config
        persistentVolumeClaim:
          claimName: deluge2-config
---
apiVersion: v1
kind: Service
metadata:
  name: deluge-tlmc
  labels:
    app: deluge-tlmc
spec:
  type: LoadBalancer
  ports:
  - port: 8112
    protocol: TCP
    name: webold
  - port: 58846
    protocol: TCP
    name: client
  selector:
    app: deluge-tlmc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deluge-tlmc-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-prod
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2.jamiechapmanbrn.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.jamiechapmanbrn.com/oauth2/start?rd=https://deluge2.jamiechapmanbrn.com"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: “true”
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: deluge2.jamiechapmanbrn.com
    http:
      paths:
        - backend:
            serviceName: deluge-tlmc
            servicePort: 8112
  tls:
  - hosts:
    - deluge2.jamiechapmanbrn.com
    secretName: deluge2.jamiechapmanbrn.com.tls     
