---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: grafana.here
    http:
      paths:
        - backend:
            serviceName: grafana
            servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: prometheus.here
    http:
      paths:
        - backend:
            serviceName: prometheus-k8s
            servicePort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: alertmanager.here
    http:
      paths:
        - backend:
            serviceName: alertmanager-main
            servicePort: 9093
