apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: washing-wasp-minecraft
    chart: minecraft-1.1.0
    heritage: Tiller
    release: washing-wasp
  name: washing-wasp-minecraft-datadir
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: rook-ssd
