apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-ssd
    volume.beta.kubernetes.io/storage-provisioner: ceph.rook.io/block
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minecraft-vanilla
    chart: minecraft-1.1.0
    heritage: Tiller
    release: manual
  name: vanilla-minecraft2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: rook-ssd
