kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ombi-config
spec:
  storageClassName:  rook-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
