kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
  namespace: default
spec:
  storageClassName:  rook-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
