apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: nginx-ingress
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jamiechapmanbrn@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-sec-prod
    # Enable HTTP01 validations
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-jamiechapmanbrn
  namespace: nginx-ingress
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jamiechapmanbrn@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-sec-prod
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: jamiechapmanbrn@hotmail.com  
            # A secretKeyRef to a cloudflare api key
            apiKeySecretRef:
              name: cloudflare-apikey
              key: apikey
    # Enable HTTP01 validations
    http01: {}